version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./migrate:/docker-entrypoint-initdb.d
  app:
    image: my-node-app
    ports:
      - 3000:3000